const data: Map<string, Array<any>> = new Map([
  [
    'TestEntity',
    [
      [
        [{ Value: 'X' }, { Value: 'O' }, { Value: ' ' }],
        [{ Value: 'X' }, { Value: 'X' }, { Value: 'O' }],
        [{ Value: 'O' }, { Value: ' ' }, { Value: 'O' }],
      ],
      [
        [{ Value: ' ' }, { Value: 'O' }, { Value: 'X' }],
        [{ Value: ' ' }, { Value: ' ' }, { Value: 'O' }],
        [{ Value: 'X' }, { Value: ' ' }, { Value: 'O' }],
      ],
      [
        [{ Value: 'X' }, { Value: 'X' }, { Value: 'O' }],
        [{ Value: 'X' }, { Value: ' ' }, { Value: 'O' }],
        [{ Value: ' ' }, { Value: 'O' }, { Value: 'O' }],
      ],
      [
        [{ Value: 'O' }, { Value: ' ' }, { Value: 'X' }],
        [{ Value: ' ' }, { Value: ' ' }, { Value: 'X' }],
        [{ Value: 'O' }, { Value: 'O' }, { Value: 'X' }],
      ],
      [
        [{ Value: 'X' }, { Value: ' ' }, { Value: ' ' }],
        [{ Value: 'X' }, { Value: 'X' }, { Value: 'X' }],
        [{ Value: 'X' }, { Value: ' ' }, { Value: ' ' }],
      ],
    ],
  ],
  [
    'SudokuEntity',
    [
      [
        [
          { Value: ' ' },
          { Value: '5' },
          { Value: ' ' },
          { Value: '4' },
          { Value: ' ' },
          { Value: ' ' },
          { Value: '1' },
          { Value: '7' },
          { Value: ' ' },
        ],
        [
          { Value: '9' },
          { Value: '4' },
          { Value: '8' },
          { Value: ' ' },
          { Value: ' ' },
          { Value: ' ' },
          { Value: ' ' },
          { Value: ' ' },
          { Value: ' ' },
        ],
        [
          { Value: ' ' },
          { Value: '7' },
          { Value: ' ' },
          { Value: ' ' },
          { Value: ' ' },
          { Value: '8' },
          { Value: '6' },
          { Value: '4' },
          { Value: ' ' },
        ],
        [
          { Value: ' ' },
          { Value: ' ' },
          { Value: '4' },
          { Value: ' ' },
          { Value: '2' },
          { Value: '3' },
          { Value: '9' },
          { Value: ' ' },
          { Value: ' ' },
        ],
        [
          { Value: ' ' },
          { Value: '8' },
          { Value: ' ' },
          { Value: ' ' },
          { Value: '4' },
          { Value: ' ' },
          { Value: ' ' },
          { Value: '6' },
          { Value: ' ' },
        ],
        [
          { Value: ' ' },
          { Value: ' ' },
          { Value: '2' },
          { Value: '8' },
          { Value: '7' },
          { Value: ' ' },
          { Value: '3' },
          { Value: ' ' },
          { Value: ' ' },
        ],
        [
          { Value: ' ' },
          { Value: '2' },
          { Value: '5' },
          { Value: '9' },
          { Value: ' ' },
          { Value: ' ' },
          { Value: ' ' },
          { Value: '1' },
          { Value: ' ' },
        ],
        [
          { Value: ' ' },
          { Value: ' ' },
          { Value: ' ' },
          { Value: ' ' },
          { Value: ' ' },
          { Value: ' ' },
          { Value: '8' },
          { Value: '2' },
          { Value: '7' },
        ],
        [
          { Value: ' ' },
          { Value: '3' },
          { Value: '7' },
          { Value: ' ' },
          { Value: ' ' },
          { Value: '4' },
          { Value: ' ' },
          { Value: '9' },
          { Value: ' ' },
        ],
      ],
    ],
  ],
]);

export default data;
