name: Full Check on Code

on: [pull_request, workflow_call]

jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn install
      - run: yarn lint
      - run: yarn package
      - run: yarn test
      - run: yarn coverage
