name: Full Check on Code

on: [push, pull_request]

jobs:
  Check Code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn install
      - run: yarn make
      - run: yarn lint
      - run: yarn test
      - run: yarn coverage
