name: Release

on:
  push:
    branches:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/check-code
      - run: yarn make
      - uses: actions/upload-artifact@v2
        with:
          name: deb
          path: out/make/deb/x64/gameapp*.deb
      - uses: actions/upload-artifact@v2
        with:
          name: rpm
          path: out/make/rpm/x64/gameapp*.rpm
      
