name: Release

on:
  push:
    branches:
      - main
      - 'release/**'

jobs:
  check:
    uses: "ryan-way/gameapp/.github/workflows/check.yaml@main"
  release:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: yarn install
      - run: yarn make
      - uses: actions/upload-artifact@v2
        with:
          name: deb
          path: out/make/deb/x64/gameapp*.deb
      - uses: actions/upload-artifact@v2
        with:
          name: rpm
          path: out/make/rpm/x64/gameapp*.rpm
      
