name: Release

on: push

jobs:
  check:
    uses: "ryan-way/gameapp/.github/workflows/check.yaml@a054ae7786a6160d1d808f3821dea695d34e8c8a"
  release:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - run: yarn make
      - uses: actions/upload-artifact@v2
        with:
          name: deb
          path: out/make/deb/x64/gameapp*.deb
      - uses: actions/upload-artifact@v2
        with:
          name: rpm
          path: out/make/rpm/x64/gameapp*.rpm
      
