name: Release

on: push

jobs:
  check:
    uses: ${{GITHUB_REPOSITORY}}/.github/workflows/check-code.yaml@${{GITHUB_REF}}
  release:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - run: yarn make
      - uses: actions/upload-artifact@v2
        with:
          name: deb
          path: out/make/deb/x64/gameapp*.deb
      - uses: actions/upload-artifact@v2
        with:
          name: rpm
          path: out/make/rpm/x64/gameapp*.rpm
      
