name: Release

on: push

jobs:
  check:
    uses: "ryan-way/gameapp/.github/workflows/check-code.yaml@d2d2bfa3d06f719637019e42d12a3f8bda20cb68"
  release:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - run: yarn make
      - uses: actions/upload-artifact@v2
        with:
          name: deb
          path: out/make/deb/x64/gameapp*.deb
      - uses: actions/upload-artifact@v2
        with:
          name: rpm
          path: out/make/rpm/x64/gameapp*.rpm
      
