on:
  push:
    branches:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/check-code
      - run: yarn make
      - uses: actions/upload-artifact@v2
        with:
          name: deb
          path: '**/*.deb'
      - uses: actions/upload-artifact@v2
        with:
          name: rpm
          path: '**/*.rpm'
      
